version: "3.7"

services:
  currency-exchange:
    image: maldini12/msv2-micro-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - rabbitmq
    environment: 
        eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.baseurl: http://zipkin-server:9411/
        RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network

  currency-conversion:
    image: maldini12/msv2-micro-conversion-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - rabbitmq
    environment: 
       eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
       spring.zipkin.baseurl: http://zipkin-server:9411/
       RABBIT_URI: amqp://guest:guest@rabbitmq:5672
       SPRING_RABBITMQ_HOST: rabbitmq
       SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network

  api-gateway:
    image: maldini12/msv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbitmq
    environment: 
       eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
       spring.zipkin.baseurl: http://zipkin-server:9411/
       RABBIT_URI: amqp://guest:guest@rabbitmq:5672
       SPRING_RABBITMQ_HOST: rabbitmq
       SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up

  naming-server:
    image:  maldini12/msv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network
    
networks:
  currency-network:
       
     
   