version: "3.7"

services:
  currency-exchange:
    image: maldini12/msv2-micro-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
    environment: 
        eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
        EUREKA.CLIENT.FETCHREGISTRY: "true"
    networks:
      - currency-network

  currency-conversion:
    image: maldini12/msv2-micro-conversion-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
    environment: 
       eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
       EUREKA.CLIENT.FETCHREGISTRY: "true"
    networks:
      - currency-network

  api-gateway:
    image: maldini12/msv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment: 
       eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
       #EUREKA.CLIENT.FETCHREGISTRY: "true"
    networks:
      - currency-network

  naming-server:
    image:  maldini12/msv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
    
networks:
  currency-network:
       
     
   